# NumPy Arrays

In [1]:
import numpy as np

**python objects:** 

- high-level number objects: integers, floating point
- containers: lists (costless insertion and append), dictionaries (fast lookup)
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

**Numpy provides:**

- extension package to Python for multi-dimensional arrays
- closer to hardware (efficiency)
- designed for scientific computation (convenience)
- Also known as array oriented computing

In [2]:
#converting list to numpy array 
lis = [1,2,3,4,5]
v = np.array(lis)
print('type of :',type(v))
print('length of v is :',len(v))

type of : <class 'numpy.ndarray'>
length of v is : 5


In [3]:
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [4]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

295 µs ± 7.05 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
a = np.arange(1000)
%timeit a**2

1.93 µs ± 79.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [6]:
#1-D
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [7]:
#print dimensions
a.ndim

1

In [8]:
#shape
a.shape

(4,)

In [9]:
len(a)

4

In [10]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [13]:
len(b) #returns the size of the first dimention

2

In [14]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
c.ndim

3

In [16]:
c.shape

(2, 2, 2)

** 1.2  Functions for creating arrays**

In [17]:
#using arrange function
# arange is an array-valued version of the built-in Python range function
a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [19]:
#using linspace
a = np.linspace(0, 1, 6) #start, end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
#An array of your choice

np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [21]:
#common arrays
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [25]:
#create array using diag function
a = np.diag([1, 2, 3, 4]) #construct a diagonal array.
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [27]:
#create array using random
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 

a

array([0.71761992, 0.88796668, 0.08313209, 0.87828783])

In [28]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([-0.845044  ,  0.88387523,  0.3236781 ,  1.49502848])

**Note:**
    
For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu



# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [29]:
a = np.arange(10)

a.dtype

dtype('int64')

In [30]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

**other datatypes**

In [32]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [33]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


In [34]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

# 3. Indexing and Slicing

**3.1 Indexing**

In [35]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [36]:
# For multidimensional arrays, indexes are tuples of integers:
a = np.diag([1, 2, 3])
print(a)
print(a[2, 2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [37]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**Slicing**

In [38]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [40]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [41]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [42]:
b = [1,2,3,4,5,6]

In [43]:
b[::-1]

[6, 5, 4, 3, 2, 1]

In [44]:
ar = np.array([[5,10,15],[20,25,30],[35,40,45]])
ar

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
ar[:2,1:]

array([[10, 15],
       [25, 30]])

# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [46]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [48]:
np.shares_memory(a, b)

True

In [49]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [50]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [51]:


a = np.arange(10)

c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [52]:
np.shares_memory(a, c)

False

In [53]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [54]:
import numpy as np
a = np.random.randint(0, 20, 15)
a

array([ 5, 14, 17, 13,  2, 10,  5,  6, 17,  5,  6,  0,  5, 19, 19])

In [55]:
mask = (a % 2 == 0)
mask

array([False,  True, False, False,  True,  True, False,  True, False,
       False,  True,  True, False, False, False])

In [56]:
extract_from_a = a[mask]

extract_from_a

array([14,  2, 10,  6,  6,  0])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [57]:
a[mask] = -1
a

array([ 5, -1, 17, 13, -1, -1,  5, -1, 17,  5, -1, -1,  5, 19, 19])

**Indexing with an array of integers**

In [58]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [60]:
# New values can be assigned 

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])