In [2]:
import numpy as np 

In [3]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [5]:
#Element Wise Addition
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [6]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [7]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [8]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [9]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [10]:
# Matrix Multiplication / Dot Products
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [11]:
#Multiplication(Dot Product) of Vectors => Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [12]:
print(a)

[1 2 3 4]


In [13]:
print(sum(a))

10


In [14]:
print(x)

[[1 2]
 [3 4]]


In [15]:
print(np.sum(x))
print(np.sum(x,axis=1))

10
[3 7]


In [16]:
# Stacking of arrays
print(a)
b = b + 5
print(b)

[1 2 3 4]
[6 7 8 9]


In [19]:
a = np.stack((a,b),axis=0)

ValueError: all input arrays must have the same shape

In [21]:
# Reshape a Numpy Array
#print(a)
a = a.reshape((-1,4))
print(a)

[[1 2 3 4]
 [6 7 8 9]]


# Some More Numpy Functions 
- min, max
- mean 
- median
- average
- variance
- standard devidation

In [22]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [25]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [26]:
c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [27]:
# Mean vs Average is Weighted
print(np.mean(c))


2.4


In [28]:
# Weights 
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))


2.4


In [29]:

# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)


1.854723699099141


In [30]:
#Inbuilt Function
dev= np.std(c)
print(dev)

1.854723699099141


In [31]:
#Variance
print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004


In [32]:
#Returns values from a Standard Normal Distributions
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

#Randoly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

[[ 0.65387768  0.45952298 -0.21767284]
 [ 0.5690407  -1.04852692 -0.42393657]]
[6 6 8]
4
